name: Keep Backend Alive

on:
  schedule:
    # Toutes les 5 minutes (GitHub Actions minimum)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Express Proxy
        run: |
          curl -f https://instagram-bot-proxy.onrender.com/api/healthz || echo "Proxy down"
          
      - name: Ping Python Bot API
        run: |
          curl -f https://instagram-bot-api-diax.onrender.com/bot-api/health || echo "Bot API down"
